services:
  db:
    container_name: db
    restart: always
    image: postgres:16-alpine
    ports:
      - 2345:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: db_recipes
      POSTGRES_DB: gotdb
      POSTGRES_USER: gotdb
      POSTGRES_PASSWORD: change_me

  api:
    container_name: api
    build:
      dockerfile: ./Dockerfile.local.gradle
    ports:
      - 8080:8080
    volumes:
      - ./api/got-demo/:app
