services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: gotdb
      POSTGRES_PASSWORD: change_me
    command: postgres -c wal_level=logical

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5552:5552"
      - "5672:5672"
    volumes:
      - type: bind
        source: ./rabbitmq/conf/rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json
      - type: bind
        source: ./rabbitmq/conf/rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf

  debezium-server:
    image: quay.io/debezium/server:2.4
    container_name: debezium-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./debezium/conf:/debezium/conf
    depends_on:
      - rabbitmq
      - postgres

  elasticsearch:
    image: elasticsearch:8.18.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=change_me
      - network.publish_host=0.0.0.0
      - xpack.security.enabled=false
      - discovery.type=single-node

  consumer:
    container_name: consumer
    image: anytimesoon/got-consumer:latest
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - rabbitmq

  api:
    container_name: api
    image: anytimesoon/got-api:latest
    ports:
      - "8090:8090"
    command: ["java", "-Dspring.datasource.url=jdbc:postgresql://postgres:5432/gotdb", "-Dspring.datasource.username=gotdb", "-Dspring.datasource.password=change_me", "-Delasticsearch.host=http://elasticsearch:9200", "-jar", "./build/libs/got-demo-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - postgres
      - elasticsearch
