services:
  db:
    restart: always
    image: postgres:16-alpine
    ports:
      - 2345:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: db_recipes
      POSTGRES_DB: gotdb
      POSTGRES_USER: gotdb
      POSTGRES_PASSWORD: change_me